#!/usr/bin/env python3
# ==========================================================================
#  WHAT THIS FILE DOES (in simple words):
#  THE CENTERPIECE of this repo - the script that assembles the whole SoC (System on a
#  Chip). Running it builds, in Python/LiteX: the clock generator (PLL: 100 MHz system
#  clock), the VexRiscv CPU with 16 KiB I/D caches, 128 KiB on-chip ROM holding the BIOS,
#  the DDR2 controller (128 MiB main RAM), UART, timer - and plugs in the two accelerator
#  peripherals (ExpLUT + GEMV) so their registers appear on the bus automatically.
#  KEY FIX (v2): the DOT8-extended CPU is swapped in with cpu.use_external_variant(),
#  NOT plain add_source() - both files define a module named 'VexRiscv', and without
#  this fix Vivado silently picks the standard CPU, dropping the DOT8 instruction
#  (firmware then crashes on the first dot8 call).
#  It outputs the generated Verilog + BIOS + csr.h; Vivado synthesis runs separately
#  on Windows (builder.build(run=False)).
#  BIG PICTURE: Run this to get every file Vivado needs to make the bitstream. This is the 'external LiteX build tree' the TinyML_algo repo refers to.
# ==========================================================================

import argparse  # CLI parsing
import os        # filesystem helpers
import sys       # interpreter/runtime helpers

from migen import ClockDomain, Module  # migen building blocks (HDL in Python)

from litex.soc.integration.builder import Builder, builder_args, builder_argdict  # build RTL + software
from litex.soc.integration.soc_core import SoCCore, soc_core_args, soc_core_argdict  # SoC core base
from litex.soc.cores.clock import S7PLL, S7IDELAYCTRL  # Xilinx 7-series PLL / IDELAY

from litex_boards.platforms import digilent_nexys4ddr  # board pinout and resources

from litedram.phy import s7ddrphy  # DDR PHY implementation for 7-series
from litedram.modules import MT47H64M16  # DDR2 memory timing module

# Import accelerator peripheral wrappers
sys.path.insert(0, os.path.join(os.path.dirname(__file__), os.pardir, "sw"))  # allow local sw/ imports
from exp_lut.litex.exp_lut_periph import ExpLUTPeriph  # local accelerator: ExpLUT
from gemv.litex.gemv_periph import GEMVPeriph        # local accelerator: GEMV


class _CRG(Module):  # Clock / Reset Generator
    def __init__(self, platform, sys_clk_freq):
        self.clock_domains.cd_sys = cd_sys = ClockDomain()  # main system clock domain
        self.clock_domains.cd_sys2x = cd_sys2x = ClockDomain()  # 2x clock used by DDR PHY
        self.clock_domains.cd_sys2x_dqs = cd_sys2x_dqs = ClockDomain(reset_less=True)  # 2x clock with phase shift for DQS
        self.clock_domains.cd_idelay = cd_idelay = ClockDomain()  # IDELAY calibration clock domain

        clk100 = platform.request("clk100")  # board 100 MHz input
        rst = ~platform.request("cpu_reset")  # active-high reset (inverted input)

        self.submodules.pll = pll = S7PLL(speedgrade=-1)  # instantiate PLL
        self.comb += pll.reset.eq(rst)  # tie PLL reset
        pll.register_clkin(clk100, 100e6)  # tell PLL input freq
        pll.create_clkout(cd_sys, sys_clk_freq)  # create sys clk
        pll.create_clkout(cd_sys2x, 2 * sys_clk_freq)  # create 2x clk for PHY
        pll.create_clkout(cd_sys2x_dqs, 2 * sys_clk_freq, phase=90)  # DQS-phase-shifted clock
        pll.create_clkout(cd_idelay, 200e6)  # 200 MHz for IDELAY

        self.submodules.idelayctrl = S7IDELAYCTRL(cd_idelay)  # IDELAYCTRL for I/O delay calibration


class BaseSoC(SoCCore):  # Main SoC: CPU, memory, peripherals
    def __init__(self, platform, sys_clk_freq,
                 rom_size=None, l2_size=None,
                 icache_size=None, dcache_size=None,
                 **kwargs):
        # Set sensible defaults
        # Path to pre-built VexRiscv_Dot8.v (generated by GenCoreDot8.scala)
        _dot8_v = os.path.join(os.path.dirname(__file__), "rtl", "VexRiscv_Dot8.v")  # external DOT8 CPU RTL
        _use_dot8_cpu = os.path.isfile(_dot8_v)  # detect if DOT8 was generated

        defaults = {
            "cpu_type": "vexriscv",         # CPU type
            "cpu_variant": "standard",      # variant (dot8 may replace)
            "with_uart": True,               # include UART peripheral
            "with_timer": True,              # include timer peripheral
            "with_cpu_icache": True,         # enable I-cache
            "with_cpu_dcache": True,         # enable D-cache
            "cpu_icache_size": icache_size or 16 * 1024,
            "cpu_dcache_size": dcache_size or 16 * 1024,
            "uart_name": "serial",         # UART backend name
            "uart_baudrate": 115200,
        }
        # ROM size: 128 KiB default
        if rom_size is None:
            rom_size = 128 * 1024
        
        defaults.update(kwargs)
        
        # Create clock/reset generator (PLLs, IDELAY)
        self.crg = _CRG(platform, sys_clk_freq)

        # Initialize SoCCore with integrated ROM only
        # DDR2 will be added as the main RAM
        super().__init__(
            platform=platform,
            clk_freq=sys_clk_freq,
            integrated_rom_size=rom_size,
            **defaults,
        )

        # DDR2 SDRAM with optional L2 cache
        # L2 cache size: 128 KiB default, configurable to 256 KiB
        if l2_size is None:
            l2_size = 128 * 1024
        
        # DDR2 PHY: 1:2 ratio (nphases=2), sys_clk=100MHz → DDR=200MHz
        # Instantiate the board-specific DDR PHY
        self.ddrphy = s7ddrphy.A7DDRPHY(
            pads=platform.request("ddram"),  # board DDR pins
            memtype="DDR2",
            nphases=2,
            sys_clk_freq=sys_clk_freq,
            iodelay_clk_freq=200e6
        )

        # Add DDR2 SDRAM as main system RAM (exposes memory at 0x80000000)
        self.add_sdram(
            "sdram",
            phy=self.ddrphy,
            module=MT47H64M16(sys_clk_freq, "1:2"),  # memory timing module
            size=0x08000000,  # 128 MB
            l2_cache_size=l2_size
        )

        # If VexRiscv_Dot8.v exists, tell LiteX to use it INSTEAD of the bundled
        # standard VexRiscv source.  Plain platform.add_source() doesn't work
        # because both files define module VexRiscv — Vivado then picks one
        # arbitrarily (and historically picks the bundled standard, dropping DOT8).
        # use_external_variant() sets self.external_variant=True, which causes
        # do_finalize() in the LiteX VexRiscv core to SKIP add_sources(), so only
        # our DOT8 file is fed to Vivado.
        # If DOT8 CPU RTL is present, use it instead of the bundled VexRiscv
        if _use_dot8_cpu:
            self.cpu.use_external_variant(_dot8_v)
            print("[INFO] DOT8 CPU variant found — using VexRiscv_Dot8.v as the VexRiscv source.")
        else:
            print("[WARN] VexRiscv_Dot8.v not found in hw/rtl/. Using standard CPU (no DOT8).")
            print("       Run Step 1-4 in the accel_all guide to build it.")

        # Add accelerator peripherals; their CSRs are exported automatically
        self.submodules.exp_lut = ExpLUTPeriph(platform, sys_clk_freq)  # exp_lut peripheral
        self.add_csr("exp_lut")
        self.submodules.gemv = GEMVPeriph(platform, sys_clk_freq)  # gemv peripheral
        self.add_csr("gemv")


def _default_sys_clk_freq(platform):
    if hasattr(platform, "default_clk_period"):
        return int(1e9 / platform.default_clk_period)
    return int(100e6)


def main() -> int:
    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
    output_dir = os.path.join(repo_root, "hw", "build")

    platform = digilent_nexys4ddr.Platform()
    if getattr(platform, "name", None) not in (None, "digilent_nexys4ddr"):
        raise ValueError(
            f"Expected platform 'digilent_nexys4ddr', got '{platform.name}'."
        )

    parser = argparse.ArgumentParser(description="LiteX SoC for Nexys4 DDR with DDR2 and Configurable Memory")
    builder_args(parser)
    soc_core_args(parser)

    parser.add_argument(
        "--sys-clk-freq",
        default=_default_sys_clk_freq(platform),
        type=float,
        help="System clock frequency in Hz (default: 100 MHz).",
    )

    parser.add_argument(
        "--rom-size",
        default=128 * 1024,
        type=int,
        help="On-chip ROM size in bytes (default: 128 KiB).",
    )

    parser.add_argument(
        "--icache-size",
        default=16 * 1024,
        type=int,
        help="Instruction cache (I-Cache) size in bytes (default: 16 KiB, min: 8 KiB).",
    )

    parser.add_argument(
        "--dcache-size",
        default=16 * 1024,
        type=int,
        help="Data cache (D-Cache) size in bytes (default: 16 KiB, min: 8 KiB).",
    )

    parser.set_defaults(
        output_dir=output_dir,
        build_name="nexys4ddr_vexriscv",
        build_backend="litex",
        l2_size=128 * 1024,  # 128 KiB default L2 cache
    )

    args = parser.parse_args()
    
    # Get SoC core arguments
    soc_core_kwargs = soc_core_argdict(args)
    soc_core_kwargs.pop("integrated_rom_size", None)
    soc_core_kwargs.pop("l2_size", None)  # Remove l2_size from soc_core_kwargs, we handle it separately
    
    rom_size = args.rom_size
    # L2 size from soc_core_args (default 128 KiB already set in parser.set_defaults)
    l2_size = getattr(args, "l2_size", 128 * 1024)
    icache_size = args.icache_size
    dcache_size = args.dcache_size
    
    # Validate memory sizes
    if rom_size < 64 * 1024:
        raise ValueError(f"ROM size must be at least 64 KiB, got {rom_size // 1024} KiB")
    if l2_size not in [128 * 1024, 256 * 1024]:
        raise ValueError(f"L2 size must be 128 KiB or 256 KiB, got {l2_size // 1024} KiB")
    if icache_size not in [8 * 1024, 16 * 1024]:
        raise ValueError(f"I-Cache size must be 8 KiB or 16 KiB, got {icache_size // 1024} KiB")
    if dcache_size not in [8 * 1024, 16 * 1024]:
        raise ValueError(f"D-Cache size must be 8 KiB or 16 KiB, got {dcache_size // 1024} KiB")
    
    soc = BaseSoC(
        platform=platform,
        sys_clk_freq=int(100e6),
        rom_size=rom_size,
        l2_size=l2_size,
        icache_size=icache_size,
        dcache_size=dcache_size,
        **soc_core_kwargs,
    )

    builder = Builder(soc, **builder_argdict(args))
    # Build software (BIOS) + generate RTL; skip Vivado synthesis (run=False).
    # Vivado must be run separately on Windows using the generated files.
    builder.build(run=False)
    print("\n[INFO] BIOS compiled and RTL generated.")
    print("[ACTION] Copy the following files to your Windows machine for Vivado synthesis:")
    gw = os.path.join(args.output_dir, "gateware")
    print(f"  - RTL (top):    {os.path.join(gw, args.build_name + '.v')}")
    print(f"  - ROM init:     {os.path.join(gw, args.build_name + '_rom.init')}")
    print(f"  - SRAM init:    {os.path.join(gw, args.build_name + '_sram.init')}")
    print(f"  - RTL (exp_lut):  {os.path.join(repo_root, 'hw', 'rtl', 'exp_lut.v')}")
    print(f"  - RTL (gemv_core): {os.path.join(repo_root, 'hw', 'rtl', 'gemv_core.v')}")
    print(f"  - Constraints:  {os.path.join(gw, 'digilent_nexys4ddr.xdc')}")
    print("[INFO] Run Vivado synthesis on Windows to generate the bitstream.")

    bitstream = os.path.join(
        args.output_dir,
        "gateware",
        f"{args.build_name}.bit",
    )
    print(f"Bitstream: {bitstream}")
    print("UART: 115200 8-N-1")
    print("\n" + "="*60)
    print("MEMORY CONFIGURATION FOR TINYML")
    print("="*60)
    print("\nMemory Map:")
    print(f"  0x00000000 - 0x{rom_size-1:08X}  [{rom_size // 1024:3d} KiB]  On-Chip ROM (BIOS)")
    print(f"  0x80000000 - 0x87FFFFFF  [128   MiB]  DDR2 SDRAM (Main RAM)")
    print("\nBRAM Allocation:")
    print(f"  L2 Cache/Scratchpad:     {l2_size // 1024:3d} KiB")
    print(f"  I-Cache (VexRiscv):      {icache_size // 1024:3d} KiB")
    print(f"  D-Cache (VexRiscv):      {dcache_size // 1024:3d} KiB")
    total_cache = l2_size + icache_size + dcache_size
    print(f"  Total Cache/BRAM Used:   {total_cache // 1024:3d} KiB")
    print(f"\nSystem Configuration:")
    print(f"  CPU: VexRiscv (standard variant)")
    print(f"  System Clock: {int(args.sys_clk_freq / 1e6)} MHz")
    print(f"  DDR Clock: {int(4 * args.sys_clk_freq / 1e6)} MHz (1:4 mode)")
    print("="*60)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
